apiVersion: apps/v1
kind: Deployment
metadata:
  name: ad-service
spec:
  selector:
    matchLabels:
      app: ad-service
  template:
    metadata:
      labels:
        app: ad-service
    spec:
      containers:
      - name: ad-service
        image: electronic-shop-microservices-ad-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 9555
        env:
        - name: PORT
          value: "9555"
---
apiVersion: v1
kind: Service
metadata:
  name: ad-service
spec:
  type: ClusterIP
  selector:
    app: ad-service
  ports:
  - port: 9555
    targetPort: 9555
