apiVersion: apps/v1
kind: Deployment
metadata:
  name: checkout-service
spec:
  selector:
    matchLabels:
      app: checkout-service
  template:
    metadata:
      labels:
        app: checkout-service
    spec:
      containers:
      - name: checkout-service
        image: electronic-shop-microservices-checkout-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 5050
        env:
        - name: PORT
          value: "5050"
        - name: PRODUCT_SERVICE_ADDR
          value: "product-service:3550"
        - name: CART_SERVICE_ADDR
          value: "cart-service:7070"
        - name: SHIPPING_SERVICE_ADDR
          value: "shipping-service:50051"
        - name: PAYMENT_SERVICE_ADDR
          value: "payment-service:50051"
        - name: CURRENCY_SERVICE_ADDR
          value: "currency-service:7000"
        - name: EMAIL_SERVICE_ADDR
          value: "email-service:8080"
---
apiVersion: v1
kind: Service
metadata:
  name: checkout-service
spec:
  type: ClusterIP
  selector:
    app: checkout-service
  ports:
  - port: 5050
    targetPort: 5050
