apiVersion: apps/v1
kind: Deployment
metadata:
  name: currency-service
spec:
  selector:
    matchLabels:
      app: currency-service
  template:
    metadata:
      labels:
        app: currency-service
    spec:
      containers:
      - name: currency-service
        image: electronic-shop-microservices-currency-service:latest
        imagePullPolicy: Never
        ports:
        - containerPort: 7000
        env:
        - name: PORT
          value: "7000"
---
apiVersion: v1
kind: Service
metadata:
  name: currency-service
spec:
  type: ClusterIP
  selector:
    app: currency-service
  ports:
  - port: 7000
    targetPort: 7000
